### ISSUE TITLE
Variable issue with Turnoff

### ISSUE THREAD

**Issue by lukemc89** [zjalexander/UpdateManagement#5]
@zjalexander 

Does this still work in 2021?
I see the turn on feature works, turn off doesn't

Environments                                                                                           Context          
------------                                                                                           -------          
{[AzureCloud, AzureCloud], [AzureChinaCloud, AzureChinaCloud], [AzureUSGovernment, AzureUSGovernment]} Microsoft.Azur...

No machines to turn off

Get-AutomationVariable : Variable not found. To create this Variable, navigate to the Variables blade and create a Variable named: PrescriptContext(numberredacted) Refer doc for more details (https://docs.microsoft.com/en-us/azure/automation/shared-resources/variables#create-and-get-a-variable) At line:86 char:13 + $variable = Get-AutomationVariable -Name $runId + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : ObjectNotFound: (:) [Get-AutomationVariable], AssetManagementClientException + FullyQualifiedErrorId : 3,Orchestrator.AssetManagement.Cmdlets.GetAutomationVariableCmdlet

**Comment by zjalexander** [comment]
I haven't tested it in a while and no longer work on the product, but I'm not aware of any changes that would break it.

The [error message you're getting](https://github.com/zjalexander/UpdateManagement/blob/master/UpdateManagement-TurnOffVms.ps1#L87) is saying the automation variable [created in the turnon script](https://github.com/zjalexander/UpdateManagement/blob/master/UpdateManagement-TurnOnVms.ps1#L125) doesn't exist.  That variable is created per runID which is [unique for each update management deployment run](https://docs.microsoft.com/en-us/azure/automation/update-management/pre-post-scripts#softwareupdateconfigurationruncontext-properties). 

If you're using two separate deployment runs, one to turn on VMs and one to turn off VMs, the solution I provided won't work as-is and you'll need to modify it for your own purposes. 

If that's not what's happening, you can look at your Automation variables to see if something's funky there.
Are there a bunch of variables you didn't create with guid-like names? That would indicate cleanup isn't working, which in turn suggests something is out of whack with how the post-script is getting invoked. 
Are you able to create your own automation variables by hand? If not, there might be a permissions issue. I don't think permissions get quite that granular, but, you know. We'll check.
If all else false, add a bunch of Write-Output statements to the scripts to trace through them and the variable values and see what is or isn't getting written out.

**Comment by lukemc89** [comment]
Thanks for that, fixed the issue this morning. Was due to the AZRM modules in the Automation account being out of date. Updating them allowed all scripts to run succesfully. Appreciate the reply
